services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - dynamodb 
      - redis
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    command:
      ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/main.ts"]
    networks:
      - app-network
   
  # DynamoDB Local service
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8080:8000"
    networks:
      - app-network
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge