version: "3.8"
services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command:
      ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]
